-- DEPRECATED
-- This file is intentionally kept as a placeholder.
-- Runtime DB initialization moved to: devops/scripts/init-db.sh
-- Reason: initialization now consumes credentials from environment variables
-- instead of hardcoded values.
