spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  lifecycle:
    timeout-per-shutdown-phase: ${SPRING_SHUTDOWN_TIMEOUT:20s}

server:
  port: ${SERVER_PORT}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
  endpoint:
    health:
      probes:
        enabled: ${MANAGEMENT_HEALTH_PROBES_ENABLED}
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS}
  info:
    env:
      enabled: true

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    version: ${APP_VERSION}
    environment: ${APP_ENV}

app:
  api:
    base-path: ${APP_API_BASE_PATH}
  version: ${APP_VERSION}
  environment: ${APP_ENV}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}
